### ISSUE TITLE
CI/CD add syntax checker for PHP

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#8]
Add in the Yml file for the GitHub Actions workflow the syntax checker for php

```yaml
    - name: PHP Syntax Checker (Lint)
      uses: StephaneBour/actions-php-lint@7.1
      with:
        dir: './src'
```
